### ISSUE TITLE
[BUG] - Visual Bugs in Create Exercise

### ISSUE THREAD

**Issue by andreaswurtz** [p7-projekt/frontend#90]
### Description

The following bugs have to be fixed:
- If there are more test cases that there is room in the pane, then the create test case button will be pushed out of the page.
- Very large compiler errors fill up the entire right pane, making it difficult to use the IDE.

DoD
- [x] Make  test case list scrollable if it surpasses pane height
- [x] Make compiler errors scrollable

### Reproduction steps

```bash
1. goto /createexercise
2. create test cases and/or make a big poopoo program
```

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added ScrollArea component to make the test case list and compiler errors scrollable, fixing the issues with content overflow in both panes.

You can review changes in this commit: https://github.com/lkilu6456546/p7-projekt-frontend-90/commit/012837ef3416f6621ef2e0f4d3e67dd44fcf4cb7.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
